# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Card Number')),
                ('card_cvv', models.CharField(max_length=4, verbose_name='Card CVV')),
                ('card_expiry_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100, verbose_name='Expiry Month')),
                ('card_expiry_year', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036')], max_length=100, verbose_name='Expiry Year')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company name')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('plan', models.CharField(choices=[('Monthly', 'Monthly - 199 EUR/month'), ('Yearly', 'Yearly - 1999 EUR/year'), ('Trial', 'Trial - 30 days')], max_length=100, verbose_name='Plan')),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
            options={
                'permissions': (('view_client', 'Can view Client'), ('modify_client', 'Can modify Client')),
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='card',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='clients.Client'),
        ),
    ]
