version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: assessment-space_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./src/staticfiles:/static
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

  web:
    build: .
    container_name: assessment-space_web
    entrypoint: /docker-entrypoint.sh
    env_file: 
      - ./src/env-staging
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./src/staticfiles:/static
    expose:
      - "8000"

  db:
    build: ./config/postgres/
    container_name: assessment-space_postgres
