# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentinterview',
            options={'permissions': (('view_assessment_interview', 'Can view AssessmentInterview'), ('edit_assessment_interview', 'Can edit AssessmentInterview'))},
        ),
        migrations.AlterModelOptions(
            name='assessmentinterviewresult',
            options={'ordering': ('-updated',), 'permissions': (('view_assessment_interview_result', 'Can view AssessmentInterviewResult'), ('edit_assessment_interview_result', 'Can edit AssessmentInterviewResult'))},
        ),
        migrations.AlterModelOptions(
            name='assessmentlogevent',
            options={'ordering': ('-created',), 'permissions': (('view_assessment_log_event', 'Can view AssessmentLogEvent'), ('edit_assessment_log_event', 'Can edit AssessmentLogEvent'))},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-user__date_joined',), 'permissions': (('view_candidate', 'Can view Candidate'), ('edit_candidate', 'Can edit Candidate'))},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-user__date_joined',), 'permissions': (('view_employee', 'Can view Employee'), ('edit_employee', 'Can edit Employee'))},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ('-start',), 'permissions': (('view_interview', 'Can view Interview'), ('edit_interview', 'Can edit Interview'))},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('-name',), 'permissions': (('view_office', 'Can view Office'), ('edit_office', 'Can edit Office'))},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('-updated',), 'permissions': (('view_result', 'Can view Result'), ('edit_result', 'Can edit Result'))},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-name',), 'permissions': (('view_room', 'Can view Room'), ('edit_room', 'Can edit Room'))},
        ),
    ]
