# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170331_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default='2017-04-02', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Make assessment details visible to everyone in the company?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='end',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
